@extends('layouts.authenticated')
@section('title', 'Alumni Directory · GradConn')
@push('styles')
<style>
.directory{max-width:1180px;margin:0 auto}.directory-hero{padding:26px;margin-bottom:18px;border-radius:22px;background:linear-gradient(135deg,#172033,#334155 60%,#f97316);color:#fff}.directory-hero h1{margin:5px 0;font-size:31px}.directory-hero p{max-width:720px;margin:0;color:#e2e8f0;line-height:1.55}.directory-eyebrow{color:#fed7aa;font-size:12px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.directory-privacy{display:flex;align-items:flex-start;gap:10px;margin-top:15px;padding:11px 13px;border:1px solid rgba(255,255,255,.2);border-radius:12px;background:rgba(255,255,255,.09);font-size:12px}.directory-filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:10px;padding:16px;margin-bottom:18px;border:1px solid #e2e8f0;border-radius:17px;background:#fff;box-shadow:0 5px 20px rgba(15,23,42,.05)}.directory-filters input,.directory-filters select{width:100%;padding:11px 12px;border:1px solid #cbd5e1;border-radius:10px;background:#fff}.directory-filters button{padding:11px 17px;border:0;border-radius:10px;background:#f97316;color:#fff;font-weight:800}.directory-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.alumni-card{padding:18px;border:1px solid #e2e8f0;border-radius:18px;background:#fff;box-shadow:0 5px 18px rgba(15,23,42,.05)}.alumni-card__top{display:flex;gap:11px;align-items:center}.alumni-initial{display:grid;width:46px;height:46px;flex:0 0 46px;place-items:center;border-radius:50%;background:linear-gradient(135deg,#fb923c,#ea580c);color:#fff;font-weight:900}.alumni-card h2{margin:0;color:#111827;font-size:17px}.alumni-card__course{margin-top:3px;color:#64748b;font-size:12px}.alumni-meta{display:flex;flex-wrap:wrap;gap:6px;margin:14px 0}.alumni-meta span{padding:5px 8px;border-radius:999px;background:#fff7ed;color:#c2410c;font-size:11px;font-weight:800}.alumni-card h3{margin:13px 0 5px;color:#475569;font-size:11px;text-transform:uppercase}.alumni-card p{margin:0;color:#475569;font-size:13px;line-height:1.55}.directory-empty{padding:55px;text-align:center;border:1px solid #e2e8f0;border-radius:18px;background:#fff;color:#64748b}.directory-pagination{margin-top:20px}.directory-pagination nav>div:first-child{display:none}@media(max-width:900px){.directory-filters{grid-template-columns:1fr 1fr}.directory-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:580px){.directory-filters,.directory-grid{grid-template-columns:1fr}.directory-hero{padding:21px}.directory-hero h1{font-size:26px}}
</style>
@endpush
@section('content')
<div class="directory">
    <header class="directory-hero"><div class="directory-eyebrow">Professional Directory</div><h1>Alumni List</h1><p>Find graduates by course, batch, and professional competencies.</p><div class="directory-privacy"><i class="fas fa-shield-halved"></i><span>Contact details and private personal information are shown only when an alumnus submits an application to one of your jobs.</span></div></header>
    <form class="directory-filters" method="GET" action="{{ route('employer.alumni_list') }}"><input name="search" value="{{ $search }}" placeholder="Search name or competencies" aria-label="Search alumni"><select name="course" aria-label="Course"><option value="">All courses</option>@foreach($courses as $option)<option value="{{ $option }}" @selected($course===$option)>{{ $option }}</option>@endforeach</select><select name="batch_year" aria-label="Batch year"><option value="">All batches</option>@foreach($batches as $option)<option value="{{ $option }}" @selected($batch===(string)$option)>{{ $option }}</option>@endforeach</select><button type="submit"><i class="fas fa-search"></i> Search</button></form>
    @if($alumni->isEmpty())<div class="directory-empty"><i class="fas fa-user-group"></i><h2>No matching alumni</h2><p>Try a different name, competency, course, or batch.</p></div>@else
    <section class="directory-grid">@foreach($alumni as $person)<article class="alumni-card"><div class="alumni-card__top"><div class="alumni-initial">{{ mb_strtoupper(mb_substr($person->fullname,0,1)) }}</div><div><h2>{{ $person->fullname }}</h2><div class="alumni-card__course">{{ $person->course ?: 'Course not provided' }}</div></div></div><div class="alumni-meta">@if($person->batch_year)<span>Batch {{ $person->batch_year }}</span>@endif @if($person->employment_status)<span>{{ $person->employment_status }}</span>@endif</div><h3>Professional Competencies</h3><p>{{ $person->skills ?: 'No competencies listed.' }}</p>@if($person->career_objective)<h3>Career Objective</h3><p>{{ \Illuminate\Support\Str::limit($person->career_objective,180) }}</p>@endif</article>@endforeach</section><div class="directory-pagination">{{ $alumni->links() }}</div>@endif
</div>
@endsection
