<?php

use App\Http\Controllers\Admin\AlumniAccountController;
use App\Http\Controllers\Admin\DestroyArchivedEventCommentController;
use App\Http\Controllers\Admin\DestroyJobController;
use App\Http\Controllers\Admin\SendApplicantResumeController;
use App\Http\Controllers\Admin\StoreAccountController;
use App\Http\Controllers\Admin\UpdateAlumniApprovalController;
use App\Http\Controllers\Alumni\DestroyEmploymentController;
use App\Http\Controllers\Alumni\RespondToOfferController;
use App\Http\Controllers\Alumni\StoreEducationController;
use App\Http\Controllers\Alumni\StoreEmploymentController;
use App\Http\Controllers\Application\AlumniApplicationActionController;
use App\Http\Controllers\Application\StoreApplicationController;
use App\Http\Controllers\Application\UpdateApplicationStatusController;
use App\Http\Controllers\Employer\AlumniDirectoryActionController;
use App\Http\Controllers\Employer\EmployerJobOfferActionController;
use App\Http\Controllers\Event\ArchiveEventController;
use App\Http\Controllers\Event\RestoreEventController;
use App\Http\Controllers\Event\StoreEventController;
use App\Http\Controllers\Event\UpdateEventController;
use App\Http\Controllers\Interview\ScheduleInterviewController;
use App\Http\Controllers\Job\SendJobNotificationController;
use App\Http\Controllers\Job\StoreJobController;
use App\Http\Controllers\Job\UpdateJobController;
use App\Http\Controllers\Pages\AdminAdminArchiveController;
use App\Http\Controllers\Pages\AdminAlumniCreateController;
use App\Http\Controllers\Pages\AdminAlumniEditController;
use App\Http\Controllers\Pages\AdminAlumniListController;
use App\Http\Controllers\Pages\AdminAlumniReportController;
use App\Http\Controllers\Pages\AdminApplicationsController;
use App\Http\Controllers\Pages\AdminCreateAlumniOfficerController;
use App\Http\Controllers\Pages\AdminCreateEmployerController;
use App\Http\Controllers\Pages\AdminDashboardController;
use App\Http\Controllers\Pages\AdminEventsCreateController;
use App\Http\Controllers\Pages\AdminEventsEditController;
use App\Http\Controllers\Pages\AdminEventsListController;
use App\Http\Controllers\Pages\AdminForwardToCompanyController;
use App\Http\Controllers\Pages\AdminGraduatesListController;
use App\Http\Controllers\Pages\AdminGraduatesReportController;
use App\Http\Controllers\Pages\AdminGraduatesStatsController;
use App\Http\Controllers\Pages\AdminInterviewController;
use App\Http\Controllers\Pages\AdminJobsCreateController;
use App\Http\Controllers\Pages\AdminJobsEditController;
use App\Http\Controllers\Pages\AdminJobsListController;
use App\Http\Controllers\Pages\AdminJobsNotifyController;
use App\Http\Controllers\Pages\AdminOffersHistoryController;
use App\Http\Controllers\Pages\AdminPendingAlumniController;
use App\Http\Controllers\Pages\AdminReportsController;
use App\Http\Controllers\Pages\AlumniAddDegreeController;
use App\Http\Controllers\Pages\AlumniApplyController;
use App\Http\Controllers\Pages\AlumniChangePasswordController;
use App\Http\Controllers\Pages\AlumniEditProfileController;
use App\Http\Controllers\Pages\AlumniEmploymentHistoryController;
use App\Http\Controllers\Pages\AlumniFeedController;
use App\Http\Controllers\Pages\AlumniJobDetailsController;
use App\Http\Controllers\Pages\AlumniJobOffersController;
use App\Http\Controllers\Pages\AlumniJobsController;
use App\Http\Controllers\Pages\AlumniMyApplicationsController;
use App\Http\Controllers\Pages\AlumniOfficerAlumniListController;
use App\Http\Controllers\Pages\AlumniOfficerArchiveController;
use App\Http\Controllers\Pages\AlumniOfficerDashboardController;
use App\Http\Controllers\Pages\AlumniOfficerEventsCreateController;
use App\Http\Controllers\Pages\AlumniOfficerEventsEditController;
use App\Http\Controllers\Pages\AlumniOfficerEventsListController;
use App\Http\Controllers\Pages\ArchiveController;
use App\Http\Controllers\Pages\EmployerAlumniListController;
use App\Http\Controllers\Pages\EmployerApplicationsController;
use App\Http\Controllers\Pages\EmployerDashboardController;
use App\Http\Controllers\Pages\EmployerInterviewController;
use App\Http\Controllers\Pages\EmployerJobOffersController;
use App\Http\Controllers\Pages\EmployerPostedJobController;
use App\Http\Controllers\Pages\EmployerPostJobController;
use App\Http\Controllers\Pages\ProfileController;
use App\Http\Controllers\Profile\DestroyCertificateController;
use App\Http\Controllers\Profile\StoreCertificateController;
use App\Http\Controllers\Profile\UpdateAccountProfileController;
use App\Http\Controllers\Profile\UpdateNotificationPreferenceController;
use App\Http\Controllers\Profile\UpdateOwnProfileController;
use App\Http\Controllers\Profile\UpdatePasswordController;
use App\Http\Controllers\SocialFeedActionController;
use Illuminate\Support\Facades\Route;

Route::get('/admin/admin_archive.php', AdminAdminArchiveController::class)->middleware('account:admin')->name('admin.admin_archive');
Route::delete('/admin/archive/events/{event}/comments/{comment}', DestroyArchivedEventCommentController::class)->middleware('account:admin')->name('admin.archive.comments.destroy');
Route::get('/admin/alumni_create.php', AdminAlumniCreateController::class)->middleware('account:admin')->name('admin.alumni_create');
Route::post('/admin/alumni', [StoreAccountController::class, 'alumni'])->middleware('account:admin')->name('admin.alumni.store');
Route::get('/admin/alumni_edit.php', AdminAlumniEditController::class)->middleware('account:admin')->name('admin.alumni_edit');
Route::put('/admin/alumni/{alumni}', [AlumniAccountController::class, 'update'])->middleware('account:admin')->name('admin.alumni.update');
Route::delete('/admin/alumni/{alumni}', [AlumniAccountController::class, 'destroy'])->middleware('account:admin')->name('admin.alumni.destroy');
Route::get('/admin/alumni_list.php', AdminAlumniListController::class)->middleware('account:admin')->name('admin.alumni_list');
Route::get('/admin/alumni_report.php', AdminAlumniReportController::class)->middleware('account:admin')->name('admin.alumni_report');
Route::get('/admin/applications.php', AdminApplicationsController::class)->middleware('account:admin')->name('admin.applications');
Route::get('/admin/create_alumni_officer.php', AdminCreateAlumniOfficerController::class)->middleware('account:admin')->name('admin.create_alumni_officer');
Route::post('/admin/alumni-officers', [StoreAccountController::class, 'officer'])->middleware('account:admin')->name('admin.alumni-officers.store');
Route::get('/admin/create_employer.php', AdminCreateEmployerController::class)->middleware('account:admin')->name('admin.create_employer');
Route::post('/admin/employers', [StoreAccountController::class, 'employer'])->middleware('account:admin')->name('admin.employers.store');
Route::get('/admin/dashboard.php', AdminDashboardController::class)->middleware('account:admin')->name('admin.dashboard');
Route::get('/admin/events_create.php', AdminEventsCreateController::class)->middleware('account:admin')->name('admin.events_create');
Route::get('/admin/events_delete.php', fn () => to_route('admin.events_list'))->middleware('account:admin')->name('admin.events_delete');
Route::get('/admin/events_edit.php', AdminEventsEditController::class)->middleware('account:admin')->name('admin.events_edit');
Route::get('/admin/events_list.php', AdminEventsListController::class)->middleware('account:admin')->name('admin.events_list');
Route::get('/admin/forward_to_company.php', AdminForwardToCompanyController::class)->middleware('account:admin')->name('admin.forward_to_company');
Route::post('/admin/applications/{application}/forward-resume', SendApplicantResumeController::class)->middleware('account:admin')->name('admin.applications.resume.send');
Route::get('/admin/graduates_list.php', AdminGraduatesListController::class)->middleware('account:admin')->name('admin.graduates_list');
Route::get('/admin/graduates_report.php', AdminGraduatesReportController::class)->middleware('account:admin')->name('admin.graduates_report');
Route::get('/admin/graduates_stats.php', AdminGraduatesStatsController::class)->middleware('account:admin')->name('admin.graduates_stats');
Route::get('/admin/interview.php', AdminInterviewController::class)->middleware('account:admin')->name('admin.interview');
Route::get('/admin/jobs_create.php', AdminJobsCreateController::class)->middleware('account:admin')->name('admin.jobs_create');
Route::get('/admin/jobs_edit.php', AdminJobsEditController::class)->middleware('account:admin')->name('admin.jobs_edit');
Route::get('/admin/jobs_list.php', AdminJobsListController::class)->middleware('account:admin')->name('admin.jobs_list');
Route::delete('/admin/jobs/{job}', DestroyJobController::class)->middleware('account:admin')->name('admin.jobs.destroy');
Route::post('/jobs', StoreJobController::class)->middleware('account:admin,employer')->name('jobs.store');
Route::put('/jobs/{job}', UpdateJobController::class)->middleware('account:admin,employer')->name('jobs.update');
Route::get('/admin/jobs_notify.php', AdminJobsNotifyController::class)->middleware('account:admin')->name('admin.jobs_notify');
Route::post('/admin/jobs/{job}/notifications', SendJobNotificationController::class)->middleware('account:admin')->name('admin.jobs.notifications.store');
Route::get('/admin/offers_history.php', AdminOffersHistoryController::class)->middleware('account:admin')->name('admin.offers_history');
Route::get('/admin/pending_alumni.php', AdminPendingAlumniController::class)->middleware('account:admin')->name('admin.pending_alumni');
Route::patch('/admin/alumni/{alumni}/approval', [UpdateAlumniApprovalController::class, 'approve'])->middleware('account:admin')->name('admin.alumni.approve');
Route::patch('/admin/alumni/{alumni}/rejection', [UpdateAlumniApprovalController::class, 'reject'])->middleware('account:admin')->name('admin.alumni.reject');
Route::get('/admin/reports.php', AdminReportsController::class)->middleware('account:admin')->name('admin.reports');
Route::get('/alumni/add_degree.php', AlumniAddDegreeController::class)->middleware('account:alumni')->name('alumni.add_degree');
Route::post('/profile/education', StoreEducationController::class)->middleware('account:alumni')->name('alumni.education.store');
Route::get('/alumni/apply.php', AlumniApplyController::class)->middleware('account:alumni')->name('alumni.apply');
Route::post('/alumni/jobs/{job}/applications', StoreApplicationController::class)->middleware('account:alumni')->name('applications.store');
Route::get('/alumni/change_password.php', AlumniChangePasswordController::class)->middleware('account:alumni')->name('alumni.change_password');
Route::get('/alumni/dashboard.php', fn () => to_route('alumni.feed'))->middleware('account:alumni')->name('alumni.dashboard');
Route::get('/alumni/edit_profile.php', AlumniEditProfileController::class)->middleware('account:alumni')->name('alumni.edit_profile');
Route::put('/profile/details', UpdateOwnProfileController::class)->middleware('account:alumni')->name('alumni.profile.update');
Route::get('/alumni/employment_history.php', AlumniEmploymentHistoryController::class)->middleware('account:alumni')->name('alumni.employment_history');
Route::post('/profile/employment', StoreEmploymentController::class)->middleware('account:alumni')->name('alumni.employment.store');
Route::delete('/alumni/employment/{employment}', DestroyEmploymentController::class)->middleware('account:alumni')->name('alumni.employment.destroy');
Route::get('/alumni/feed.php', AlumniFeedController::class)->middleware('account:alumni')->name('alumni.feed');
Route::get('/alumni/job_details.php', AlumniJobDetailsController::class)->middleware('account:alumni')->name('alumni.job_details');
Route::get('/alumni/job_offers.php', AlumniJobOffersController::class)->middleware('account:alumni')->name('alumni.job_offers');
Route::get('/alumni/offers/{token}/{action}', [RespondToOfferController::class, 'confirm'])->whereIn('action', ['accept', 'decline'])->middleware('account:alumni')->name('offers.response.confirm');
Route::patch('/alumni/offers/{token}/{action}', [RespondToOfferController::class, 'update'])->whereIn('action', ['accept', 'decline'])->middleware('account:alumni')->name('offers.response.update');
Route::get('/alumni/jobs.php', AlumniJobsController::class)->middleware('account:alumni')->name('alumni.jobs');
Route::get('/alumni/my_applications.php', AlumniMyApplicationsController::class)->middleware('account:alumni')->name('alumni.my_applications');
Route::patch('/alumni/applications/{application}/cancel', [AlumniApplicationActionController::class, 'cancel'])->middleware('account:alumni')->name('applications.cancel');
Route::delete('/alumni/applications/{application}', [AlumniApplicationActionController::class, 'destroy'])->middleware('account:alumni')->name('applications.destroy');
Route::get('/alumni_officer/alumni_list.php', AlumniOfficerAlumniListController::class)->middleware('account:alumni_officer')->name('alumni_officer.alumni_list');
Route::get('/alumni_officer/archive.php', AlumniOfficerArchiveController::class)->middleware('account:alumni_officer')->name('alumni_officer.archive');
Route::get('/alumni_officer/dashboard.php', AlumniOfficerDashboardController::class)->middleware('account:alumni_officer')->name('alumni_officer.dashboard');
Route::get('/alumni_officer/events_create.php', AlumniOfficerEventsCreateController::class)->middleware('account:alumni_officer')->name('alumni_officer.events_create');
Route::get('/alumni_officer/events_edit.php', AlumniOfficerEventsEditController::class)->middleware('account:alumni_officer')->name('alumni_officer.events_edit');
Route::get('/alumni_officer/events_list.php', AlumniOfficerEventsListController::class)->middleware('account:alumni_officer')->name('alumni_officer.events_list');
Route::get('/employer/alumni_list.php', EmployerAlumniListController::class)->middleware('account:employer')->name('employer.alumni_list');
Route::post('/employer/alumni-searches', [AlumniDirectoryActionController::class, 'search'])->middleware('account:employer')->name('employer.alumni.search-log');
Route::post('/employer/offers', [AlumniDirectoryActionController::class, 'offer'])->middleware('account:employer')->name('employer.offers.store');
Route::get('/employer/applications.php', EmployerApplicationsController::class)->middleware('account:employer')->name('employer.applications');
Route::get('/employer/dashboard.php', EmployerDashboardController::class)->middleware('account:employer')->name('employer.dashboard');
Route::get('/employer/interview.php', EmployerInterviewController::class)->middleware('account:employer')->name('employer.interview');
Route::get('/employer/job_offers.php', EmployerJobOffersController::class)->middleware('account:employer')->name('employer.job_offers');
Route::patch('/employer/offers/{offer}/done', [EmployerJobOfferActionController::class, 'update'])->middleware('account:employer')->name('employer.offers.done');
Route::delete('/employer/offers/{offer}', [EmployerJobOfferActionController::class, 'destroy'])->middleware('account:employer')->name('employer.offers.destroy');
Route::get('/employer/post_job.php', EmployerPostJobController::class)->middleware('account:employer')->name('employer.post_job');
Route::get('/employer/posted_job.php', EmployerPostedJobController::class)->middleware('account:employer')->name('employer.posted_job');
Route::get('/profile.php', ProfileController::class)->middleware('account')->name('profile');
Route::patch('/profile/notifications', UpdateNotificationPreferenceController::class)->middleware('account:alumni')->name('profile.notifications.update');
Route::post('/profile/certificates', StoreCertificateController::class)->middleware('account:alumni')->name('profile.certificates.store');
Route::put('/profile', UpdateAccountProfileController::class)->middleware('account')->name('profile.update');
Route::put('/profile/password', UpdatePasswordController::class)->middleware('account')->name('profile.password.update');
Route::patch('/applications/{application}/status', UpdateApplicationStatusController::class)->middleware('account:admin,employer')->name('applications.status.update');
Route::post('/interviews', ScheduleInterviewController::class)->middleware('account:admin,employer')->name('interviews.store');
Route::delete('/profile/certificates/{certificate}', DestroyCertificateController::class)->middleware('account')->name('profile.certificates.destroy');
Route::get('/events', function () {
    return match (request()->user()->role) {
        'admin' => to_route('admin.events_list'),
        'alumni_officer' => to_route('alumni_officer.events_list'),
        'alumni' => to_route('alumni.feed'),
        default => to_route('employer.dashboard'),
    };
})->middleware('account')->name('events.index');
Route::patch('/events/{event}/restore', RestoreEventController::class)->middleware('account')->name('events.restore');
Route::patch('/events/{event}/archive', ArchiveEventController::class)->middleware('account')->name('events.archive');
Route::post('/events', StoreEventController::class)->middleware('account')->name('events.store');
Route::post('/feed/{type}/{post}/reaction', [SocialFeedActionController::class, 'reaction'])->where('type', 'event')->middleware('account:admin,alumni,alumni_officer')->name('feed.reactions.store');
Route::post('/feed/{type}/{post}/comments', [SocialFeedActionController::class, 'comment'])->where('type', 'event')->middleware('account:admin,alumni,alumni_officer')->name('feed.comments.store');
Route::delete('/feed/comments/{comment}', [SocialFeedActionController::class, 'destroyComment'])->middleware('account:admin,alumni,alumni_officer')->name('feed.comments.destroy');
Route::put('/events/{event}', UpdateEventController::class)->middleware('account')->name('events.update');
Route::get('/archive.php', ArchiveController::class)->middleware('account:alumni_officer')->name('archive');
