@extends('layouts.authenticated')
@section('title', 'Alumni Officer Dashboard · GradConn')
@push('styles')
<style>
.officer-dashboard{max-width:1180px;margin:0 auto}.officer-hero{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:30px;margin-bottom:20px;border-radius:24px;background:linear-gradient(135deg,#172033,#334155 55%,#f97316);box-shadow:0 18px 42px rgba(15,23,42,.16);color:#fff}.officer-hero__eyebrow{font-size:12px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:#fed7aa}.officer-hero h1{margin:7px 0;font-size:34px}.officer-hero p{max-width:620px;margin:0;color:#e2e8f0}.officer-actions{display:flex;flex-wrap:wrap;gap:10px}.officer-button{display:inline-flex;align-items:center;gap:8px;padding:11px 15px;border:1px solid rgba(255,255,255,.3);border-radius:12px;background:rgba(255,255,255,.12);color:#fff;text-decoration:none;font-weight:800}.officer-button--primary{border-color:#fb923c;background:#f97316}.officer-button:hover{background:#fff;color:#c2410c}.officer-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:20px}.officer-stat{padding:19px;border:1px solid #e2e8f0;border-radius:18px;background:#fff;box-shadow:0 6px 22px rgba(15,23,42,.06)}.officer-stat i{color:#f97316}.officer-stat span{display:block;margin-top:12px;color:#64748b;font-size:12px;font-weight:800;text-transform:uppercase}.officer-stat strong{display:block;margin-top:3px;color:#111827;font-size:30px}.officer-panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:20px;background:#fff;box-shadow:0 6px 22px rgba(15,23,42,.06)}.officer-panel__header{display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid #eef2f7}.officer-panel__header h2{margin:0;font-size:19px}.officer-panel__header a,.officer-row-actions a{color:#ea580c;font-weight:800;text-decoration:none}.officer-table{width:100%;border-collapse:collapse}.officer-table th,.officer-table td{padding:14px 20px;border-bottom:1px solid #eef2f7;text-align:left}.officer-table th{background:#f8fafc;color:#64748b;font-size:11px;text-transform:uppercase}.officer-category{display:inline-flex;padding:5px 9px;border-radius:999px;background:#fff7ed;color:#c2410c;font-size:11px;font-weight:800}.officer-row-actions{display:flex;gap:8px}.officer-row-actions a{font-size:12px}.officer-empty{padding:44px;text-align:center;color:#64748b}@media(max-width:900px){.officer-hero{align-items:flex-start;flex-direction:column}.officer-stats{grid-template-columns:repeat(2,1fr)}.officer-table-wrap{overflow-x:auto}}@media(max-width:520px){.officer-hero{padding:22px}.officer-hero h1{font-size:27px}.officer-stat{padding:15px}}
</style>
@endpush
@section('content')
<div class="officer-dashboard">
<section class="officer-hero"><div><div class="officer-hero__eyebrow">Alumni Officer Workspace</div><h1>Welcome, {{ $fullname }}</h1><p>Publish community updates, moderate discussions, and keep alumni informed from one workspace.</p></div><div class="officer-actions"><a class="officer-button officer-button--primary" href="{{ route('alumni_officer.events_create') }}"><i class="fas fa-plus"></i> Create Post</a><a class="officer-button" href="{{ route('profile', ['tab' => 'security']) }}"><i class="fas fa-lock"></i> Change Password</a></div></section>
<section class="officer-stats"><article class="officer-stat"><i class="fas fa-pen-to-square"></i><span>Posts by you</span><strong>{{ number_format($myEvents) }}</strong></article><article class="officer-stat"><i class="fas fa-circle-check"></i><span>Active posts</span><strong>{{ number_format($activeEvents) }}</strong></article><article class="officer-stat"><i class="fas fa-clock"></i><span>Scheduled</span><strong>{{ number_format($scheduledEvents) }}</strong></article><article class="officer-stat"><i class="fas fa-box-archive"></i><span>Archived</span><strong>{{ number_format($archivedEvents) }}</strong></article></section>
<section class="officer-panel"><header class="officer-panel__header"><h2>Recent Community Posts</h2><a href="{{ route('alumni_officer.events_list') }}">Open feed <i class="fas fa-arrow-right"></i></a></header>
@if(empty($recentEvents))<div class="officer-empty"><i class="far fa-newspaper"></i><p>No community posts yet.</p></div>@else<div class="officer-table-wrap"><table class="officer-table"><thead><tr><th>Post</th><th>Type</th><th>Publisher</th><th>Published</th><th>Action</th></tr></thead><tbody>
@foreach($recentEvents as $event)<tr><td><strong>{{ $event['title'] ?: 'Untitled post' }}</strong></td><td><span class="officer-category">{{ ucfirst($event['category'] ?? 'announcement') }}</span></td><td>{{ $event['poster_name'] ?: 'GradConn' }}</td><td>{{ \App\Support\ViewFormatter::alumni_officer_dashboard_format_date($event['created_at'] ?? null) }}</td><td><div class="officer-row-actions"><a href="{{ route('alumni_officer.events_list') }}#post-event-{{ $event['id'] }}">View</a>@if((int)$event['posted_by'] === $officer_id)<a href="{{ route('alumni_officer.events_edit', ['id' => $event['id']]) }}">Edit</a><form method="POST" action="{{ route('events.destroy', $event['id']) }}" onsubmit="return confirm('Delete this post permanently?')">@csrf @method('DELETE')<button class="link danger" type="submit">Delete</button></form>@endif</div></td></tr>@endforeach
</tbody></table></div>@endif</section>
</div>
@endsection
